### ISSUE TITLE
In PostDetails Page

### ISSUE THREAD

**Issue by mohamad3607** [st249/Learning#3]
برای مثال
"دانلود آهنگ جدید محسن چاوشی به نام شرح الف"
به تگ h1 تبدیل شود 
درحال حاضر h2 است

دانلود آهنگ جدید به صفحه 
https://mamedia.ir/Home/Tracks/
لینک شود

قسمتی از ترانه  به " قسمتی از ترانه - نام خواننده و نام آهنگ - تغییر کند

متن ترانه به " متن ترانه آهنگ نام خواننده + و نام آهنگ "تغییر کند

**Comment by st249** [comment]
این آخریه چیه؟؟؟

**Comment by mohamad3607** [comment]
کدوم آخری؟
    On Saturday, March 28, 2020, 01:41:31 AM GMT+4:30, HBakhshi <notifications@github.com> wrote:  
 
 


این آخریه چیه؟؟؟

**Comment by st249** [comment]
قسمتی از ترانه به " قسمتی از ترانه - نام خواننده و نام آهنگ - تغییر کند

,va khte badish

**Comment by st249** [comment]
2 ta morede aval 2rost shod

**Comment by mohamad3607** [comment]
بیا واتس اپ

**Comment by st249** [comment]
لطفی اون Pull request رو دوباره ایجاد کن 
اگر نمیشه دوباره اون متن رو بزن

**Comment by st249** [comment]
قبلش سایت رو ببین البته

**Comment by st249** [comment]
Check and close issue
